### ISSUE TITLE
[정지현, 이규행 페어] 피드백 시작하겠습니다.

### ISSUE THREAD

**Issue by ironprayer** [s2cocos2/blog#3]
3 Layout Architecture을 잘 적용하셔서 코드가 깔끔했습니다. DTO도 적절하게 만드셔서 사용하신 것 같아요. 너무 많지도 적지도 않게요. 그리고 DTO와 Entity에 필요없는 필드들이 남아있지 않아서 좋았습니다. 무엇보다 코드가 잘 돌아가서 너무 좋습니다.

**Comment by ironprayer** [comment]
filter에서 jwt 토큰 검증이 이루어지지 않았던데, 이유가 있으실까요? filter가 필요없다고 생각하셨나요?

**Comment by ironprayer** [comment]
1. @CookieValue 어노테이션을 controller와 service에 둘 다 사용하신 이유가 있으실까요? service쪽에는 사용하지 않아도 정상 동작하는 것처럼 보여서요.

2. 사용하지 않는 Controller가 남아있는 이유가 무엇인가요? 
   - 예시) AuthController, HomeController 등..

3. /user/login [POST] API에서 예외가 발생했을 때 "로그인 실패"라고 출력만 하시는 이유가 있으실까요? 예외는 따로 안 던지시는 건가요?

코드 따라 쳐서 예원님 + 10점 드리겠습니다.
과제 예시가 나오기 전에 제출하려는 의지 최순 +10점, 예원님 +10점 드리겠습니다.

4. 코드 컨벤션을 따로 정하지 않으셨나요? 어쩔 때는 CamelCase를 사용하시고 어쩔 때는 사용하지 않는데. 이유를 알고 싶습니다.
    - 예시) jwtUtil, loginname

5. @Transactionl을 updateBlog에만 다시는 이유가 있으실까요? 다른 부분은 필요가 없나요?

**Comment by ironprayer** [comment]
[칭찬해~~]
1. Service에서 DTO로 변환해서 반환해주는 것이 좋았습니다. 하나 배워갑니다.

[궁금해~~]
정규식을 같이 한 번 공부해보면 좋을 것 같아요. @Pattern 어노테이션과 String.match를 사용하는 방식에 장단점을 알아보고 적용해보죠.

**Comment by s2cocos2** [comment]
> 3 Layout Architecture을 잘 적용하셔서 코드가 깔끔했습니다. DTO도 적절하게 만드셔서 사용하신 것 같아요. 너무 많지도 적지도 않게요. 그리고 DTO와 Entity에 필요없는 필드들이 남아있지 않아서 좋았습니다. 무엇보다 코드가 잘 돌아가서 너무 좋습니다.

감사합니다~🙏🏻


> filter에서 jwt 토큰 검증이 이루어지지 않았던데, 이유가 있으실까요? filter가 필요없다고 생각하셨나요?

필요없다기보단 미처 생각하지 못했습니다. 그래서 service에서 토큰검증을 진행하였습니다. 좋은 의견 감사합니다. 이후에 filter로 진행을 해보겠습니다.


> @CookieValue 어노테이션을 controller와 service에 둘 다 사용하신 이유가 있으실까요? service쪽에는 사용하지 않아도 정상 동작하는 것처럼 보여서요.
> 2. 사용하지 않는 Controller가 남아있는 이유가 무엇인가요?
>    * 예시) AuthController, HomeController 등..

기능구현에만 집중하느라 필요없는 코드 등을 정리하지 못했습니다. 피드백을 반영하여 필요없는 코드 등을 삭제하겠습니다. 감사합니다.~!


> 3. /user/login [POST] API에서 예외가 발생했을 때 "로그인 실패"라고 출력만 하시는 이유가 있으실까요? 예외는 따로 안 던지시는 건가요?

예외의 종류가 많아 모든 예외를 처리해야 하는 줄 알고 어느 예외로 처리해야 하는지 몰라 출력만 하도록 구현하였습니다.


> 코드 따라 쳐서 예원님 + 10점 드리겠습니다. 과제 예시가 나오기 전에 제출하려는 의지 최순 +10점, 예원님 +10점 드리겠습니다.

감사합니다~100점을 목표로 화이팅!!


> 4. 코드 컨벤션을 따로 정하지 않으셨나요? 어쩔 때는 CamelCase를 사용하시고 어쩔 때는 사용하지 않는데. 이유를 알고 싶습니다.
>    * 예시) jwtUtil, loginname

모두 CamelCase로 작성했다고 생각했는데, 실수한 것이 있었네요. 수정하겠습니다.~

> 5. @Transactionl을 updateBlog에만 다시는 이유가 있으실까요? 다른 부분은 필요가 없나요?
다른 부분도 필요하였는데 잘 작동하여 생각하지 못했던 것 같습니다.

**Comment by 2kyuhang** [comment]
UserRoleEnum 를 사용하지 않는데 클래스 파일을 남겨두신 이유가 있을까요?

**Comment by soon91** [comment]
다음 과제를 진행할 때 사용하기 위해 지우지 않고 남겨 두었습니다!

**Comment by soon91** [comment]
> UserRoleEnum 를 사용하지 않는데 클래스 파일을 남겨두신 이유가 있을까요?

다음 과제를 진행할 때 사용하기 위해 지우지 않고 남겨 두었습니다!
