### ISSUE TITLE
[이해찬,최서림 페어]코드리뷰

### ISSUE THREAD

**Issue by Bebeqwer** [s2cocos2/blog#4]

**Comment by haechanlee96** [comment]
안녕하세요! 

가독성이 높고 패키지별로 파일이 한눈에 알아볼 수 있게 정리가 되어 있는 것 같습니다. 코드는 깔끔하게 정리되어 있고, 각 메서드와 변수의 이름도 그 기능을 잘 설명하고 있어 가독성이 좋습니다!

UserController의 login 메서드에서 로그인 실패 시 System.out.println을 이용하여 로그를 출력하고 있습니다. 이 부분에서는 예외를 던지거나, 사용자에게 오류 메시지를 반환하는 것은 어떻게 생각하시는지요? @SLF4J 를 활용한 'log.error' 나 'log.warn' 의 사용이 조금 더 추후에 확장성이 있는걸로 알고 있습니다!

UnsupportedEncodingException이 발생하면, 현재 RuntimeException을 던지고 있는데 `CustomException`을 사용하여 사용자 정의 예외를 사용하는것은 어떻게 생각하시나요?? 어떤 상황에서 예외가 발생했는지 더 잘 파악할 수 있지 않을까 하는 생각도 들었습니다!

**Comment by s2cocos2** [comment]
UserController의 login 메서드에서 로그인 실패 시 System.out.println을 이용하여 로그를 출력하고 있습니다. 이 부분에서는 예외를 던지거나, 사용자에게 오류 메시지를 반환하는 것은 어떻게 생각하시는지요? @slf4j 를 활용한 'log.error' 나 'log.warn' 의 사용이 조금 더 추후에 확장성이 있는걸로 알고 있습니다!
-> 지현님, 규행님께서도 같은 이슈를 남겨주셔서 수정할 예정입니다. 다시 답변을 해보자면 처리해야할 예외의 종류가 많아서 어떤 예외를 선택해야할지 몰라 오류메시지만 반환하였습니다.

**Comment by s2cocos2** [comment]
UnsupportedEncodingException이 발생하면, 현재 RuntimeException을 던지고 있는데 CustomException을 사용하여 사용자 정의 예외를 사용하는것은 어떻게 생각하시나요?? 어떤 상황에서 예외가 발생했는지 더 잘 파악할 수 있지 않을까 하는 생각도 들었습니다!
-> 여기는 어느부분을 말씀하시는 걸까요?

**Comment by haechanlee96** [comment]
// Response 객체에 Cookie 추가
            res.addCookie(cookie);
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e.getMessage());
            
AuthController 밑에 예외부분 입니다

**Comment by s2cocos2** [comment]
AuthController를 사용하지 않아 그 부분에 대한 코드는 강의내용에 있는 코드를 변경하지 않고 그대로 사용하였습니다. 나중에 AuthController를 사용하게 되면 의견반영하여 예외처리하도록 해보겠습니다!
